### ISSUE TITLE
Contact us form broken

### ISSUE THREAD

**Issue by bmazerolle** [SENG426-Summer-2022/vega-web-master#11]
**Description**
There are 3 issues present on the contact us form: 
* The form does not submit an email anywhere
* The email regex that tests for an @ is present on the name input
* There is no empty message enforcement

**Reproduction steps**
Steps to reproduce the behaviour:
1. Go to the contact us page
2. Enter a name (with no @ in it)
3. Enter a valid email
4. Leave message blank

You will note that:
1. The name input asks for an @ to be present
2. The form submits even with a blank message
3. The form doesn't actually go anywhere

**Expected behaviour**
1. Name must be a non-empty value with no special character or numbers
2. Email must be non-empty value with @ and . in it (ie <name>@<domain>.<country code>)
3. Message must be non-blank with character limit (maybe 1000?)

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/31942169/170893532-dc6a1bb5-32d6-44ea-8f2a-c45ef420304c.png)

**Story points**
5

**Comment by ACHultman** [comment]
Actual: 8
