### ISSUE TITLE
Site logo too padded

### ISSUE THREAD

**Issue by bmazerolle** [SENG426-Summer-2022/vega-web-master#12]
**Description**
The Vega logo at the top of the website has too much bottom padding.

**Reproduction steps**
Steps to reproduce the behaviour:
1. Go to any page on the Vega site
2. Look at the top logo. At present the container is 168px.

**Expected behaviour**
The "container" div containing the log should be about 100px to accomodate the present size. I think we should cut it down to 70px as the current logo is massive.

**Additional context / Screenshots**
<img width="788" alt="Screen Shot 2022-05-29 at 3 24 24 PM" src="https://user-images.githubusercontent.com/31942169/170893692-27cb525a-9012-41ad-99b2-eeaaece404a0.png">

**Story points**
2

**Comment by ACHultman** [comment]
Actual time: 2
