### ISSUE TITLE
Password manager not implemented

### ISSUE THREAD

**Issue by bmazerolle** [SENG426-Summer-2022/vega-web-master#21]
**Feature description**
We need to implement a password manager to accomodate for password changes on admin/staff/user accounts. This should be added to the account path.

**Proposed solution**
1. Rename nav bar link from "logout" to "account"
2. Add a container containing two password inputs and a submission button to that /account path
3. Add front-end verification that the entered passwords match
4. Add front-end password encoding and send to /changepassword backend endpoint (to be implemented)

**Describe alternatives you've considered**
* Might want to add minimum password requirements
* Can cut down to one password input but 2 is good to ensure user knows what password they set

**Additional context**
N/A

** Story points **
5

**Comment by ACHultman** [comment]
Actual time: 8
