### ISSUE TITLE
Add user crud

### ISSUE THREAD

**Issue by Gavinok** [SENG426-Summer-2022/vega-web-master#33]
**Feature description**
Add a feature where the admin can manage (add, edit, delete) users from the admin panel

**Proposed solution**
- Edit the admin panel page to include a new "Manage User" button
- This button should redirect to a new dedicated page where the admin can edit user details or delete the user.
- Also have a separate button where the admin can add a user.

**Additional context**
- If time permits have a confirmation message display before deleting a user.

**Story points**
13

**Comment by ACHultman** [comment]
Actual time: 21
