### ISSUE TITLE
Vega Absolute Vault Secrets List/Homepage

### ISSUE THREAD

**Issue by Gavinok** [SENG426-Summer-2022/vega-web-master#6]
**Feature description**
This is the core of the  Vault Absolute Vault feature. The Vega Absolute Vault provides users a way to view, create, modify, delete, and share encrypted data. This page will offer links to perform the above actions.

**Proposed solution**
The page will contain a vertical list of secrets (only displaying the name of the secret and it's date) with a button to `View`, `Modify`, `Delete`, or `Share` each of the secrets. In addition a button labelled `Create New Secret` will take them to an additional interface for creating a new secret.

When the `View` option is selected the secret's name, and the name of the user will be sent to the backend requesting the contents of that secret. When the encrypted contents are received from the backend they will be encrypted and inserted below the secret in the listing.

When the `Modify` button is selected the user will be taken to the New Secret Page with the url postfixed by the name of the secret to be modified.

These secrets are just those that have been shared or owned by them. For this reason operations such as Delete, Modify and Share  will not work unless the user was the original creator of that secret.

**Describe alternatives you've considered**
An alternative to having three buttons next to each secret we could instead have a right click menu offering each of these choices. 

**Additional context**
The link to this page, the creation, modification, and deletion of secrets is handled on a dedicated page.

**Story points**
13

**Comment by ACHultman** [comment]
Feature dropped from development
