### ISSUE TITLE
Add Vega Absolute Vault To Nav Bar

### ISSUE THREAD

**Issue by Gavinok** [SENG426-Summer-2022/vega-web-master#7]
**Feature description**
Add a link to the Vega Absolute Vault in the top navigation bar

**Proposed solution**
A clear and concise description of how to accomplish this feature.
Add a link entry to the top navigatoin bar that will bring users to the Vega Absolute Vault page. Only making this available when the Customer or Staff is logged in. This would be provided as a static url endpoint.

**Additional context**
This feature is dependant on the Vega Absolute Vault and requires #6 

**Story points**
1

**Comment by ACHultman** [comment]
Feature dropped from development
