### ISSUE TITLE
Vega Absolute Vault New Secret Page

### ISSUE THREAD

**Issue by Gavinok** [SENG426-Summer-2022/vega-web-master#8]
**Feature description**
This feature adds support for creating new Secrets to be stored in the Vega Absolute Vault.

**Proposed solution**
This page will be accesed as url endpoint. The page will have 1 text box for the user to enter the name for the secret. A
optional text box for the user to enter their secrets content as text. Alternatively there will also be a button labelled "Upload Secret As File" which will open the users file picker the user can use to select their secret. Finally there will a confirmation button at the bottom of the page labelled `Create Secret`.

All secrets must have a unique name unless this either text or a file to be stored. When the `Create Secret` button has been clicked and the content matches the above restrictions the content will be encrypted and sent to the backend to be stored.

If the url is postfixed with a key then that key will be overwritten by this content and will not allow the user to set the name of the secret to anything except the postfixed string.

**Describe alternatives you've considered**
Instead of having a text input and a file input we could just have a file upload option or a textbox that supports drag and drop.

**Additional context**
These secrets can be examined via the Vega Absolute Vault Home Page #6 

**Story points**
5

**Comment by ACHultman** [comment]
Feature dropped from development
