### ISSUE TITLE
Vega Absolute Vault Secret Sending

### ISSUE THREAD

**Issue by Gavinok** [SENG426-Summer-2022/vega-web-master#9]
**Feature description**
Customers and Staff should be able to share the ability to `View` secrets with one and other. This page will offer users an interface this

**Proposed solution**
The url will be postfixed by the name of the secret to be shared. The page will display the following a text box to enter the email of the user they would like to share their secret with. If that email is valid an encrypted message will be sent to the database asking for the given email to be given read access to the given secret. If that email is not registered or the secret could not be found then we will receive an error and notify the user. If the operation was successful notify the user and return to the Absolute Vault Homepage.

**Describe alternatives you've considered**
Alternatively this could be integrated into the Absolute Vault Homepage like the viewing of secrets is in #6 .

**Additional context**
This depends on the spring backend allowing for both read and write options existing rather than a global option since we do not want to allow those being shared the content to have the option to delete this link. In addition, we should not allow users who only have read access to share a given secret.

**Story points**
13

**Comment by ACHultman** [comment]
Feature dropped from development
